<div class="row-fluid">
	<div class="">
		<div class="col-sm-4">
			
				<!--<div class="widget-header">
					<h4 class="widget-title">Custom File Input</h4>

					<div class="widget-toolbar">
						<a href="#" data-action="collapse">
							<i class="ace-icon fa fa-chevron-up"></i>
						</a>

						<a href="#" data-action="close">
							<i class="ace-icon fa fa-times"></i>
						</a>
					</div>
				</div>-->
				<div class="">
					<div class="widget-main">
						<div class="form-group">
							<div class="col-xs-12">
								<!-- #section:custom/file-input -->
								<input type="file" id="id-input-file-2" />
							</div>
						</div>

						<!--<div class="form-group">
							<div class="col-xs-12">
								<input multiple="" type="file" id="id-input-file-3" />

								<!-- /section:custom/file-input -->
							<!--</div>
						</div>-->

						<!-- #section:custom/file-input.filter -->
						<label>
							<input type="checkbox" name="file-format" id="id-file-format" class="ace" />
							<!--<span class="lbl"> Allow only images</span>-->
						</label>

						<!-- /section:custom/file-input.filter -->
					</div>
				</div>
			
		</div>
	</div>
</div>
<hr />
<div class="">
	<div class="col-xs-8">
		<div class="progress progress-striped active">
			<div class="progress-bar progress-bar-yellow" style="width: 60%"></div>
		</div>
	</div>
</div>
<!-- inline scripts related to this page -->
<script type="text/javascript">
jQuery(function($) {
	$('#id-input-file-1 , #id-input-file-2').ace_file_input({
		no_file:'Seleccione Archivo CSV ...',
		btn_choose:'Subir',
		btn_change:'Cambiar',
		droppable:false,
		onchange:null,
		thumbnail:false //| true | large
		//whitelist:'gif|png|jpg|jpeg'
		//blacklist:'exe|php'
		//onchange:''
		//
	});
});
</script>